version: '3.9'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ~/repositories/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=realestate